In [1]:
import os
from dotenv import load_dotenv
import pandas as pd
import geopandas as gpd
from sqlalchemy import create_engine

In [2]:
load_dotenv(dotenv_path=".env")
db = os.getenv("db_url")
engine = create_engine(db)

In [3]:
nyc = pd.read_sql("SELECT ur20, area, isoperi, solidity, rectan, pop_den, geom FROM public.nyc", con=engine)
la = pd.read_sql("SELECT ur20, area, isoperi, solidity, rectan, pop_den, geom FROM public.la", con=engine)
chicago = pd.read_sql("SELECT ur20, area, isoperi, solidity, rectan, pop_den, geom FROM public.chicago", con=engine)
bay = pd.read_sql("SELECT ur20, area, isoperi, solidity, rectan, pop_den, geom FROM public.bay", con=engine)
dallas = pd.read_sql("SELECT ur20, area, isoperi, solidity, rectan, pop_den, geom FROM public.dallas", con=engine)
dc = pd.read_sql("SELECT ur20, area, isoperi, solidity, rectan, pop_den, geom FROM public.dc", con=engine)
houston = pd.read_sql("SELECT ur20, area, isoperi, solidity, rectan, pop_den, geom FROM public.houston", con=engine)
boston = pd.read_sql("SELECT ur20, area, isoperi, solidity, rectan, pop_den, geom FROM public.boston", con=engine)
atlanta = pd.read_sql("SELECT ur20, area, isoperi, solidity, rectan, pop_den, geom FROM public.atlanta", con=engine)
seattle = pd.read_sql("SELECT ur20, area, isoperi, solidity, rectan, pop_den, geom FROM public.seattle", con=engine)

In [4]:
nyc['city'] = 'nyc'
la['city'] = 'la'
chicago['city'] = 'chicago'
bay['city'] = 'bay'
dallas['city'] = 'dallas'
dc['city'] = 'dc'
houston['city'] = 'houston'
boston['city'] = 'boston'
atlanta['city'] = 'atlanta'
seattle['city'] = 'seattle'

In [5]:
combined = pd.concat([nyc, la, chicago, bay, dallas, dc, houston, boston, atlanta, seattle]).reset_index(drop=True)
filtered = combined.loc[combined['city']=='nyc']
filtered

ur20       area  isoperi  solidity  rectan    pop_den  \
0         U  16200.825    0.697     1.000   0.956  28616.003   
1         U  24292.633    0.609     1.000   0.949   8742.396   
2         U  19628.887    0.663     1.000   0.964  10555.762   
3         U  15393.900    0.561     1.000   0.979   7739.343   
4         U  14438.490    0.654     1.000   0.903  80365.333   
...     ...        ...      ...       ...     ...        ...   
122510    U   1207.169    0.099     0.987   0.917      0.000   
122511    U  26240.455    0.478     0.983   0.804   6415.748   
122512    U  26385.473    0.645     0.972   0.890   8638.202   
122513    U  12150.579    0.616     1.000   0.979   9378.609   
122514    U  19083.806    0.358     0.901   0.774   8278.625   

                                                     geom city  
0       0106000020E61000000100000001030000000100000005...  nyc  
1       0106000020E61000000100000001030000000100000005...  nyc  
2       0106000020E61000000100000001030000000100000005...  nyc  
3       0106000020E61000000100000001030000000100000005...  nyc  
4       0106000020E61000000100000001030000000100000005...  nyc  
...                                                   ...  ...  
122510  0106000020E6100000010000000103000000010000000A...  nyc  
122511  0106000020E61000000100000001030000000100000007...  nyc  
122512  0106000020E6100000010000000103000000010000000D...  nyc  
122513  0106000020E61000000100000001030000000100000005...  nyc  
122514  0106000020E6100000010000000103000000010000001F...  nyc  

[122515 rows x 8 columns]

In [6]:
import pandas as pd
import numpy as np
import torch
from torch_geometric.data import Data
from shapely import wkb, wkt
from shapely.geometry import Polygon, MultiPolygon,LinearRing

def parse_geom(g):
    return wkb.loads(bytes.fromhex(g))

def _turning_angle(p_prev, p, p_next):
    v1 = p_prev - p
    v2 = p_next - p
    n1 = np.linalg.norm(v1) + 1e-12
    n2 = np.linalg.norm(v2) + 1e-12
    cosang = np.clip(np.dot(v1, v2) / (n1 * n2), -1.0, 1.0)
    return np.arccos(cosang)

def polygon_to_graph(poly, y_value=None):
    poly = wkb.loads(bytes.fromhex(poly))

    if isinstance(poly, MultiPolygon):
        poly = max(poly.geoms, key=lambda p: p.area)

    ring = LinearRing(poly.exterior.coords)
    coords = np.array(ring.coords[:-1], dtype=np.float32)
    n = coords.shape[0]
    # if n < 3:
    #     return None

    centroid = coords.mean(axis=0, keepdims=True)
    coords0 = coords - centroid
    scale = np.sqrt((poly.area if poly.area > 0 else 1.0))
    coords0 = coords0 / (scale + 1e-12)

    prev_idx = (np.arange(n) - 1) % n
    next_idx = (np.arange(n) + 1) % n

    angles = np.array(
        [_turning_angle(coords0[prev_idx[i]], coords0[i], coords0[next_idx[i]]) for i in range(n)],
        dtype=np.float32
    )

    e_prev = np.linalg.norm(coords0 - coords0[prev_idx], axis=1).astype(np.float32)
    e_next = np.linalg.norm(coords0[next_idx] - coords0, axis=1).astype(np.float32)
    elen = np.stack([e_prev, e_next], axis=1)

    x = np.concatenate([coords0, angles[:, None], elen], axis=1)   # 5 features of each node: (x coordinate, y coordinate, angle, edge length 1, edge length 2)
    x = torch.from_numpy(x)

    src = torch.arange(n, dtype=torch.long)
    dst = torch.from_numpy(next_idx.astype(np.int64))
    edge_index = torch.stack([torch.cat([src, dst]), torch.cat([dst, src])], dim=0)

    data = Data(x=x, edge_index=edge_index)
    if y_value is not None:
        data.y = torch.tensor([float(y_value)], dtype=torch.float32)
    return data

c:\Users\kdgki\anaconda3\envs\geospatial\Lib\site-packages\torch_geometric\__init__.py:4: UserWarning: An issue occurred while importing 'pyg-lib'. Disabling its usage. Stacktrace: Could not load this library: C:\Users\kdgki\anaconda3\envs\geospatial\Lib\site-packages\libpyg.pyd
  import torch_geometric.typing
c:\Users\kdgki\anaconda3\envs\geospatial\Lib\site-packages\torch_geometric\__init__.py:4: UserWarning: An issue occurred while importing 'torch-scatter'. Disabling its usage. Stacktrace: Could not load this library: C:\Users\kdgki\anaconda3\envs\geospatial\Lib\site-packages\torch_scatter\_version_cuda.pyd
  import torch_geometric.typing
c:\Users\kdgki\anaconda3\envs\geospatial\Lib\site-packages\torch_geometric\__init__.py:4: UserWarning: An issue occurred while importing 'torch-cluster'. Disabling its usage. Stacktrace: Could not load this library: C:\Users\kdgki\anaconda3\envs\geospatial\Lib\site-packages\torch_cluster\_version_cuda.pyd
  import torch_geometric.typing
c:\Users\k

In [7]:
filtered["graph"] = filtered["geom"].apply(polygon_to_graph)

C:\Users\kdgki\AppData\Local\Temp\ipykernel_49936\3561659828.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered["graph"] = filtered["geom"].apply(polygon_to_graph)


In [8]:
filtered

ur20       area  isoperi  solidity  rectan    pop_den  \
0         U  16200.825    0.697     1.000   0.956  28616.003   
1         U  24292.633    0.609     1.000   0.949   8742.396   
2         U  19628.887    0.663     1.000   0.964  10555.762   
3         U  15393.900    0.561     1.000   0.979   7739.343   
4         U  14438.490    0.654     1.000   0.903  80365.333   
...     ...        ...      ...       ...     ...        ...   
122510    U   1207.169    0.099     0.987   0.917      0.000   
122511    U  26240.455    0.478     0.983   0.804   6415.748   
122512    U  26385.473    0.645     0.972   0.890   8638.202   
122513    U  12150.579    0.616     1.000   0.979   9378.609   
122514    U  19083.806    0.358     0.901   0.774   8278.625   

                                                     geom city  \
0       0106000020E61000000100000001030000000100000005...  nyc   
1       0106000020E61000000100000001030000000100000005...  nyc   
2       0106000020E61000000100000001030000000100000005...  nyc   
3       0106000020E61000000100000001030000000100000005...  nyc   
4       0106000020E61000000100000001030000000100000005...  nyc   
...                                                   ...  ...   
122510  0106000020E6100000010000000103000000010000000A...  nyc   
122511  0106000020E61000000100000001030000000100000007...  nyc   
122512  0106000020E6100000010000000103000000010000000D...  nyc   
122513  0106000020E61000000100000001030000000100000005...  nyc   
122514  0106000020E6100000010000000103000000010000001F...  nyc   

                                                    graph  
0       [(x, [tensor([-0.2087,  0.7334,  1.6551,  1.41...  
1       [(x, [tensor([-0.0095,  0.8443,  1.7148,  1.66...  
2       [(x, [tensor([-0.1794,  0.7782,  1.6553,  1.51...  
3       [(x, [tensor([-0.9450,  0.2050,  1.5157,  0.54...  
4       [(x, [tensor([-0.8181, -0.3691,  1.3325,  0.67...  
...                                                   ...  
122510  [(x, [tensor([-2.9138, -0.3084,  1.9168,  0.19...  
122511  [(x, [tensor([-1.0040,  0.0434,  3.1118,  0.41...  
122512  [(x, [tensor([-0.4232, -0.0432,  2.8995,  0.11...  
122513  [(x, [tensor([-0.8584,  0.2414,  1.5201,  0.60...  
122514  [(x, [tensor([-0.3479, -0.8349,  2.5664,  0.24...  

[122515 rows x 9 columns]

In [20]:
from torch.utils.data import Dataset
from torch_geometric.loader import DataLoader

class GraphTabularDataset(Dataset):
    def __init__(self, df):
        self.df = df
        self.feature_cols = ["area", "isoperi", "solidity", "rectan"]
        self.target_col = "pop_den"

    def __len__(self):
        return len(self.df)

    def __getitem__(self, i):
        row = self.df.iloc[i]
        g = row["graph"]
        tab = torch.tensor(row[self.feature_cols].to_numpy(dtype="float32"))
        y = torch.tensor([float(row[self.target_col])], dtype=torch.float32)

        g = g.clone()
        g.tab = tab
        g.y = y
        return g

dataset = GraphTabularDataset(filtered)
loader = DataLoader(dataset, batch_size=512, shuffle=True)

In [21]:
print(dataset[1])  
print(dataset[1].x)
print(dataset[1].edge_index)
print(dataset[1].tab)
print(dataset[1].y)

Data(x=[4, 5], edge_index=[2, 8], tab=[4], y=[1])
tensor([[-0.0095,  0.8443,  1.7148,  1.6644,  0.6112],
        [ 0.5882,  0.7163,  1.4236,  0.6112,  1.6639],
        [ 0.0047, -0.8420,  1.7202,  1.6639,  0.6061],
        [-0.5882, -0.7163,  1.4246,  0.6061,  1.6644]])
tensor([[0, 1, 2, 3, 1, 2, 3, 0],
        [1, 2, 3, 0, 0, 1, 2, 3]])
tensor([2.4293e+04, 6.0900e-01, 1.0000e+00, 9.4900e-01])
tensor([8742.3965])


In [22]:
nodes = []
edges = []
for i in range(1000):
    g = dataset[i]
    nodes.append(g.num_nodes)
    edges.append(g.edge_index.size(1))

print(min(nodes), max(nodes), sum(nodes)/len(nodes))
print(min(edges), max(edges), sum(edges)/len(edges))

3 1524 38.706
6 3048 77.412


# Graph Training Model

In [23]:
import torch
import torch.nn as nn
from torch_geometric.nn import GCNConv, global_mean_pool

class GraphTabModel(nn.Module):
    def __init__(self, node_in_dim: int, tab_dim: int, gnn_hidden: int = 64, mlp_hidden: int = 64):
        super().__init__()
        self.conv1 = GCNConv(node_in_dim, gnn_hidden)
        self.conv2 = GCNConv(gnn_hidden, gnn_hidden)
        in_dim = gnn_hidden + tab_dim
        self.mlp = nn.Sequential(
            nn.Linear(in_dim, mlp_hidden),
            nn.ReLU(),
            nn.Linear(mlp_hidden, 1),
        )

    def forward(self, batch):
        x = self.conv1(batch.x, batch.edge_index)
        x = torch.relu(x)
        x = self.conv2(x, batch.edge_index)
        x = torch.relu(x)

        g = global_mean_pool(x, batch.batch)

        tab = batch.tab
        if tab.dim() == 1:
            tab = tab.view(g.size(0), -1)

        z = torch.cat([g, tab], dim=1)
        return self.mlp(z)


device = torch.device("cuda")
node_in_dim = dataset[0].x.size(1)
tab_dim = 4

model = GraphTabModel(node_in_dim=node_in_dim, tab_dim=tab_dim).to(device)
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)
loss_fn = nn.MSELoss()

model.train()
for epoch in range(30):
    total_loss = 0.0
    for batch in loader:
        batch = batch.to(device)
        pred = model(batch)
        yb = batch.y.view(-1, 1)
        loss = loss_fn(pred, yb)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        total_loss += loss.item() * yb.size(0)
    avg_loss = total_loss / len(loader.dataset)
    print(f"Epoch {epoch+1}: train MSE = {avg_loss:.4f}")

Epoch 1: train MSE = 1441716336.0850
Epoch 2: train MSE = 1171523925.0035
Epoch 3: train MSE = 1022522225.2938
Epoch 4: train MSE = 980711618.1622
Epoch 5: train MSE = 967010459.1630
Epoch 6: train MSE = 962813758.1252
Epoch 7: train MSE = 961924133.9032
Epoch 8: train MSE = 959033848.7530
Epoch 9: train MSE = 957506802.7690
Epoch 10: train MSE = 956055659.1229
Epoch 11: train MSE = 960261921.2195
Epoch 12: train MSE = 954492689.4236
Epoch 13: train MSE = 954391263.7882
Epoch 14: train MSE = 954544205.6719
Epoch 15: train MSE = 953076275.3489
Epoch 16: train MSE = 951918517.9446
Epoch 17: train MSE = 951174763.8025
Epoch 18: train MSE = 951774674.4159
Epoch 19: train MSE = 958895890.6084
Epoch 20: train MSE = 949771898.2162
Epoch 21: train MSE = 949880973.4875
Epoch 22: train MSE = 949312152.7057
Epoch 23: train MSE = 948941258.1695
Epoch 24: train MSE = 948527196.7897
Epoch 25: train MSE = 949198524.6682
Epoch 26: train MSE = 953229904.5095
Epoch 27: train MSE = 947765602.3964
Epoch 2

# Evaluation for nn tuning

In [24]:
model.eval()
pred_loader = DataLoader(dataset, batch_size=2048, shuffle=False, num_workers=0, pin_memory=True)

all_pred = []
with torch.inference_mode():
    for batch in pred_loader:
        batch = batch.to(device)
        pred = model(batch).view(-1).detach().cpu().numpy()
        all_pred.append(pred)

filtered["y_pred"] = np.concatenate(all_pred)

C:\Users\kdgki\AppData\Local\Temp\ipykernel_49936\876383157.py:11: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered["y_pred"] = np.concatenate(all_pred)


In [25]:
filtered

ur20       area  isoperi  solidity  rectan    pop_den  \
0         U  16200.825    0.697     1.000   0.956  28616.003   
1         U  24292.633    0.609     1.000   0.949   8742.396   
2         U  19628.887    0.663     1.000   0.964  10555.762   
3         U  15393.900    0.561     1.000   0.979   7739.343   
4         U  14438.490    0.654     1.000   0.903  80365.333   
...     ...        ...      ...       ...     ...        ...   
122510    U   1207.169    0.099     0.987   0.917      0.000   
122511    U  26240.455    0.478     0.983   0.804   6415.748   
122512    U  26385.473    0.645     0.972   0.890   8638.202   
122513    U  12150.579    0.616     1.000   0.979   9378.609   
122514    U  19083.806    0.358     0.901   0.774   8278.625   

                                                     geom city  \
0       0106000020E61000000100000001030000000100000005...  nyc   
1       0106000020E61000000100000001030000000100000005...  nyc   
2       0106000020E61000000100000001030000000100000005...  nyc   
3       0106000020E61000000100000001030000000100000005...  nyc   
4       0106000020E61000000100000001030000000100000005...  nyc   
...                                                   ...  ...   
122510  0106000020E6100000010000000103000000010000000A...  nyc   
122511  0106000020E61000000100000001030000000100000007...  nyc   
122512  0106000020E6100000010000000103000000010000000D...  nyc   
122513  0106000020E61000000100000001030000000100000005...  nyc   
122514  0106000020E6100000010000000103000000010000001F...  nyc   

                                                    graph        y_pred  
0       [(x, [tensor([-0.2087,  0.7334,  1.6551,  1.41...  35522.273438  
1       [(x, [tensor([-0.0095,  0.8443,  1.7148,  1.66...  35549.042969  
2       [(x, [tensor([-0.1794,  0.7782,  1.6553,  1.51...  35542.582031  
3       [(x, [tensor([-0.9450,  0.2050,  1.5157,  0.54...  37821.578125  
4       [(x, [tensor([-0.8181, -0.3691,  1.3325,  0.67...  35285.628906  
...                                                   ...           ...  
122510  [(x, [tensor([-2.9138, -0.3084,  1.9168,  0.19...  -8016.092285  
122511  [(x, [tensor([-1.0040,  0.0434,  3.1118,  0.41...  24844.720703  
122512  [(x, [tensor([-0.4232, -0.0432,  2.8995,  0.11...  13610.047852  
122513  [(x, [tensor([-0.8584,  0.2414,  1.5201,  0.60...  37219.246094  
122514  [(x, [tensor([-0.3479, -0.8349,  2.5664,  0.24...   2152.924072  

[122515 rows x 10 columns]

In [26]:
import numpy as np

y_true = filtered["pop_den"].to_numpy(dtype=float)
y_pred = filtered["y_pred"].to_numpy(dtype=float)

ss_res = np.sum((y_true - y_pred) ** 2)
ss_tot = np.sum((y_true - y_true.mean()) ** 2)

r2 = 1.0 - ss_res / (ss_tot + 1e-12)

print("R2:", r2)


R2: 0.12725329920769235
